### ISSUE TITLE
Postgres container throwing error "Postgress instance not initialized. Super User password can not be empty"

### ISSUE THREAD

**Issue by virendrawali** [airavata-courses/Blitzkrieg#52]

**Comment by shindedarshan** [comment]
This was the issue with the environment variables that I was trying to pass to the container. Now I have added these environment variables into the Kubernetes deployment file instead of the docker-compose file. 
There is one more change I have done for this, instead of using postgres:10 docker image directly, I have used normal ubuntu image and installed Postgres server in it using dockerfile.  
These changes have resolved this issue. Now Postgres server is starting correctly and user-management microservice is able to communicate with it without any issue.

**Comment by shindedarshan** [comment]
Adding @virendrawali for reviewing the code change. And adding a label of Pending for code review.

**Comment by shindedarshan** [comment]
Code changes made to fix this issue has resolved issue #44.

**Comment by virendrawali** [comment]
looks good.
